/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as PublicLogoutImport } from './routes/_public/logout'
import { Route as PublicAuthImport } from './routes/_public/auth'
import { Route as AuthenticatedUsersImport } from './routes/_authenticated/users'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedGameImport } from './routes/_authenticated/game'
import { Route as Authenticated403Import } from './routes/_authenticated/403'
import { Route as PublicAuthVerifyEmailImport } from './routes/_public/auth/verify-email'
import { Route as AuthenticatedUsersIdImport } from './routes/_authenticated/users/$id'
import { Route as AuthenticatedGameSpellsImport } from './routes/_authenticated/game/spells'
import { Route as AuthenticatedGameRankingImport } from './routes/_authenticated/game/ranking'
import { Route as AuthenticatedGamePlayImport } from './routes/_authenticated/game/play'
import { Route as AuthenticatedGameGuideImport } from './routes/_authenticated/game/guide'
import { Route as AuthenticatedGameCraftingImport } from './routes/_authenticated/game/crafting'
import { Route as AuthenticatedGameCemeteryImport } from './routes/_authenticated/game/cemetery'
import { Route as AuthenticatedGamePlayShopImport } from './routes/_authenticated/game/play/shop'
import { Route as AuthenticatedGamePlayInventoryImport } from './routes/_authenticated/game/play/inventory'
import { Route as AuthenticatedGamePlayHubImport } from './routes/_authenticated/game/play/hub'
import { Route as AuthenticatedGamePlayEquipmentImport } from './routes/_authenticated/game/play/equipment'
import { Route as AuthenticatedGamePlayCharacterStatsImport } from './routes/_authenticated/game/play/character-stats'
import { Route as AuthenticatedGamePlayEquipmentSelectImport } from './routes/_authenticated/game/play/equipment/select'
import { Route as AuthenticatedGamePlayBattleCharacterImport } from './routes/_authenticated/game/play/battle/$character'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicLogoutRoute = PublicLogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => PublicRoute,
} as any)

const PublicAuthRoute = PublicAuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRoute,
} as any)

const AuthenticatedUsersRoute = AuthenticatedUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedGameRoute = AuthenticatedGameImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const Authenticated403Route = Authenticated403Import.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const PublicAuthVerifyEmailRoute = PublicAuthVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicAuthRoute,
} as any)

const AuthenticatedUsersIdRoute = AuthenticatedUsersIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)

const AuthenticatedGameSpellsRoute = AuthenticatedGameSpellsImport.update({
  id: '/spells',
  path: '/spells',
  getParentRoute: () => AuthenticatedGameRoute,
} as any)

const AuthenticatedGameRankingRoute = AuthenticatedGameRankingImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedGameRoute,
} as any)

const AuthenticatedGamePlayRoute = AuthenticatedGamePlayImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedGameRoute,
} as any)

const AuthenticatedGameGuideRoute = AuthenticatedGameGuideImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedGameRoute,
} as any)

const AuthenticatedGameCraftingRoute = AuthenticatedGameCraftingImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => AuthenticatedGameRoute,
} as any)

const AuthenticatedGameCemeteryRoute = AuthenticatedGameCemeteryImport.update({
  id: '/cemetery',
  path: '/cemetery',
  getParentRoute: () => AuthenticatedGameRoute,
} as any)

const AuthenticatedGamePlayShopRoute = AuthenticatedGamePlayShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedGamePlayRoute,
} as any)

const AuthenticatedGamePlayInventoryRoute =
  AuthenticatedGamePlayInventoryImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedGamePlayRoute,
  } as any)

const AuthenticatedGamePlayHubRoute = AuthenticatedGamePlayHubImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedGamePlayRoute,
} as any)

const AuthenticatedGamePlayEquipmentRoute =
  AuthenticatedGamePlayEquipmentImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthenticatedGamePlayRoute,
  } as any)

const AuthenticatedGamePlayCharacterStatsRoute =
  AuthenticatedGamePlayCharacterStatsImport.update({
    id: '/character-stats',
    path: '/character-stats',
    getParentRoute: () => AuthenticatedGamePlayRoute,
  } as any)

const AuthenticatedGamePlayEquipmentSelectRoute =
  AuthenticatedGamePlayEquipmentSelectImport.update({
    id: '/select',
    path: '/select',
    getParentRoute: () => AuthenticatedGamePlayEquipmentRoute,
  } as any)

const AuthenticatedGamePlayBattleCharacterRoute =
  AuthenticatedGamePlayBattleCharacterImport.update({
    id: '/battle/$character',
    path: '/battle/$character',
    getParentRoute: () => AuthenticatedGamePlayRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/403': {
      id: '/_authenticated/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Authenticated403Import
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/game': {
      id: '/_authenticated/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AuthenticatedGameImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthImport
      parentRoute: typeof PublicImport
    }
    '/_public/logout': {
      id: '/_public/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof PublicLogoutImport
      parentRoute: typeof PublicImport
    }
    '/_authenticated/game/cemetery': {
      id: '/_authenticated/game/cemetery'
      path: '/cemetery'
      fullPath: '/game/cemetery'
      preLoaderRoute: typeof AuthenticatedGameCemeteryImport
      parentRoute: typeof AuthenticatedGameImport
    }
    '/_authenticated/game/crafting': {
      id: '/_authenticated/game/crafting'
      path: '/crafting'
      fullPath: '/game/crafting'
      preLoaderRoute: typeof AuthenticatedGameCraftingImport
      parentRoute: typeof AuthenticatedGameImport
    }
    '/_authenticated/game/guide': {
      id: '/_authenticated/game/guide'
      path: '/guide'
      fullPath: '/game/guide'
      preLoaderRoute: typeof AuthenticatedGameGuideImport
      parentRoute: typeof AuthenticatedGameImport
    }
    '/_authenticated/game/play': {
      id: '/_authenticated/game/play'
      path: '/play'
      fullPath: '/game/play'
      preLoaderRoute: typeof AuthenticatedGamePlayImport
      parentRoute: typeof AuthenticatedGameImport
    }
    '/_authenticated/game/ranking': {
      id: '/_authenticated/game/ranking'
      path: '/ranking'
      fullPath: '/game/ranking'
      preLoaderRoute: typeof AuthenticatedGameRankingImport
      parentRoute: typeof AuthenticatedGameImport
    }
    '/_authenticated/game/spells': {
      id: '/_authenticated/game/spells'
      path: '/spells'
      fullPath: '/game/spells'
      preLoaderRoute: typeof AuthenticatedGameSpellsImport
      parentRoute: typeof AuthenticatedGameImport
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdImport
      parentRoute: typeof AuthenticatedUsersImport
    }
    '/_public/auth/verify-email': {
      id: '/_public/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof PublicAuthVerifyEmailImport
      parentRoute: typeof PublicAuthImport
    }
    '/_authenticated/game/play/character-stats': {
      id: '/_authenticated/game/play/character-stats'
      path: '/character-stats'
      fullPath: '/game/play/character-stats'
      preLoaderRoute: typeof AuthenticatedGamePlayCharacterStatsImport
      parentRoute: typeof AuthenticatedGamePlayImport
    }
    '/_authenticated/game/play/equipment': {
      id: '/_authenticated/game/play/equipment'
      path: '/equipment'
      fullPath: '/game/play/equipment'
      preLoaderRoute: typeof AuthenticatedGamePlayEquipmentImport
      parentRoute: typeof AuthenticatedGamePlayImport
    }
    '/_authenticated/game/play/hub': {
      id: '/_authenticated/game/play/hub'
      path: '/hub'
      fullPath: '/game/play/hub'
      preLoaderRoute: typeof AuthenticatedGamePlayHubImport
      parentRoute: typeof AuthenticatedGamePlayImport
    }
    '/_authenticated/game/play/inventory': {
      id: '/_authenticated/game/play/inventory'
      path: '/inventory'
      fullPath: '/game/play/inventory'
      preLoaderRoute: typeof AuthenticatedGamePlayInventoryImport
      parentRoute: typeof AuthenticatedGamePlayImport
    }
    '/_authenticated/game/play/shop': {
      id: '/_authenticated/game/play/shop'
      path: '/shop'
      fullPath: '/game/play/shop'
      preLoaderRoute: typeof AuthenticatedGamePlayShopImport
      parentRoute: typeof AuthenticatedGamePlayImport
    }
    '/_authenticated/game/play/battle/$character': {
      id: '/_authenticated/game/play/battle/$character'
      path: '/battle/$character'
      fullPath: '/game/play/battle/$character'
      preLoaderRoute: typeof AuthenticatedGamePlayBattleCharacterImport
      parentRoute: typeof AuthenticatedGamePlayImport
    }
    '/_authenticated/game/play/equipment/select': {
      id: '/_authenticated/game/play/equipment/select'
      path: '/select'
      fullPath: '/game/play/equipment/select'
      preLoaderRoute: typeof AuthenticatedGamePlayEquipmentSelectImport
      parentRoute: typeof AuthenticatedGamePlayEquipmentImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedGamePlayEquipmentRouteChildren {
  AuthenticatedGamePlayEquipmentSelectRoute: typeof AuthenticatedGamePlayEquipmentSelectRoute
}

const AuthenticatedGamePlayEquipmentRouteChildren: AuthenticatedGamePlayEquipmentRouteChildren =
  {
    AuthenticatedGamePlayEquipmentSelectRoute:
      AuthenticatedGamePlayEquipmentSelectRoute,
  }

const AuthenticatedGamePlayEquipmentRouteWithChildren =
  AuthenticatedGamePlayEquipmentRoute._addFileChildren(
    AuthenticatedGamePlayEquipmentRouteChildren,
  )

interface AuthenticatedGamePlayRouteChildren {
  AuthenticatedGamePlayCharacterStatsRoute: typeof AuthenticatedGamePlayCharacterStatsRoute
  AuthenticatedGamePlayEquipmentRoute: typeof AuthenticatedGamePlayEquipmentRouteWithChildren
  AuthenticatedGamePlayHubRoute: typeof AuthenticatedGamePlayHubRoute
  AuthenticatedGamePlayInventoryRoute: typeof AuthenticatedGamePlayInventoryRoute
  AuthenticatedGamePlayShopRoute: typeof AuthenticatedGamePlayShopRoute
  AuthenticatedGamePlayBattleCharacterRoute: typeof AuthenticatedGamePlayBattleCharacterRoute
}

const AuthenticatedGamePlayRouteChildren: AuthenticatedGamePlayRouteChildren = {
  AuthenticatedGamePlayCharacterStatsRoute:
    AuthenticatedGamePlayCharacterStatsRoute,
  AuthenticatedGamePlayEquipmentRoute:
    AuthenticatedGamePlayEquipmentRouteWithChildren,
  AuthenticatedGamePlayHubRoute: AuthenticatedGamePlayHubRoute,
  AuthenticatedGamePlayInventoryRoute: AuthenticatedGamePlayInventoryRoute,
  AuthenticatedGamePlayShopRoute: AuthenticatedGamePlayShopRoute,
  AuthenticatedGamePlayBattleCharacterRoute:
    AuthenticatedGamePlayBattleCharacterRoute,
}

const AuthenticatedGamePlayRouteWithChildren =
  AuthenticatedGamePlayRoute._addFileChildren(
    AuthenticatedGamePlayRouteChildren,
  )

interface AuthenticatedGameRouteChildren {
  AuthenticatedGameCemeteryRoute: typeof AuthenticatedGameCemeteryRoute
  AuthenticatedGameCraftingRoute: typeof AuthenticatedGameCraftingRoute
  AuthenticatedGameGuideRoute: typeof AuthenticatedGameGuideRoute
  AuthenticatedGamePlayRoute: typeof AuthenticatedGamePlayRouteWithChildren
  AuthenticatedGameRankingRoute: typeof AuthenticatedGameRankingRoute
  AuthenticatedGameSpellsRoute: typeof AuthenticatedGameSpellsRoute
}

const AuthenticatedGameRouteChildren: AuthenticatedGameRouteChildren = {
  AuthenticatedGameCemeteryRoute: AuthenticatedGameCemeteryRoute,
  AuthenticatedGameCraftingRoute: AuthenticatedGameCraftingRoute,
  AuthenticatedGameGuideRoute: AuthenticatedGameGuideRoute,
  AuthenticatedGamePlayRoute: AuthenticatedGamePlayRouteWithChildren,
  AuthenticatedGameRankingRoute: AuthenticatedGameRankingRoute,
  AuthenticatedGameSpellsRoute: AuthenticatedGameSpellsRoute,
}

const AuthenticatedGameRouteWithChildren =
  AuthenticatedGameRoute._addFileChildren(AuthenticatedGameRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  Authenticated403Route: typeof Authenticated403Route
  AuthenticatedGameRoute: typeof AuthenticatedGameRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  Authenticated403Route: Authenticated403Route,
  AuthenticatedGameRoute: AuthenticatedGameRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicAuthRouteChildren {
  PublicAuthVerifyEmailRoute: typeof PublicAuthVerifyEmailRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthVerifyEmailRoute: PublicAuthVerifyEmailRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicLogoutRoute: typeof PublicLogoutRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicLogoutRoute: PublicLogoutRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/403': typeof Authenticated403Route
  '/game': typeof AuthenticatedGameRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/auth': typeof PublicAuthRouteWithChildren
  '/logout': typeof PublicLogoutRoute
  '/game/cemetery': typeof AuthenticatedGameCemeteryRoute
  '/game/crafting': typeof AuthenticatedGameCraftingRoute
  '/game/guide': typeof AuthenticatedGameGuideRoute
  '/game/play': typeof AuthenticatedGamePlayRouteWithChildren
  '/game/ranking': typeof AuthenticatedGameRankingRoute
  '/game/spells': typeof AuthenticatedGameSpellsRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/auth/verify-email': typeof PublicAuthVerifyEmailRoute
  '/game/play/character-stats': typeof AuthenticatedGamePlayCharacterStatsRoute
  '/game/play/equipment': typeof AuthenticatedGamePlayEquipmentRouteWithChildren
  '/game/play/hub': typeof AuthenticatedGamePlayHubRoute
  '/game/play/inventory': typeof AuthenticatedGamePlayInventoryRoute
  '/game/play/shop': typeof AuthenticatedGamePlayShopRoute
  '/game/play/battle/$character': typeof AuthenticatedGamePlayBattleCharacterRoute
  '/game/play/equipment/select': typeof AuthenticatedGamePlayEquipmentSelectRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/403': typeof Authenticated403Route
  '/game': typeof AuthenticatedGameRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/auth': typeof PublicAuthRouteWithChildren
  '/logout': typeof PublicLogoutRoute
  '/game/cemetery': typeof AuthenticatedGameCemeteryRoute
  '/game/crafting': typeof AuthenticatedGameCraftingRoute
  '/game/guide': typeof AuthenticatedGameGuideRoute
  '/game/play': typeof AuthenticatedGamePlayRouteWithChildren
  '/game/ranking': typeof AuthenticatedGameRankingRoute
  '/game/spells': typeof AuthenticatedGameSpellsRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/auth/verify-email': typeof PublicAuthVerifyEmailRoute
  '/game/play/character-stats': typeof AuthenticatedGamePlayCharacterStatsRoute
  '/game/play/equipment': typeof AuthenticatedGamePlayEquipmentRouteWithChildren
  '/game/play/hub': typeof AuthenticatedGamePlayHubRoute
  '/game/play/inventory': typeof AuthenticatedGamePlayInventoryRoute
  '/game/play/shop': typeof AuthenticatedGamePlayShopRoute
  '/game/play/battle/$character': typeof AuthenticatedGamePlayBattleCharacterRoute
  '/game/play/equipment/select': typeof AuthenticatedGamePlayEquipmentSelectRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/403': typeof Authenticated403Route
  '/_authenticated/game': typeof AuthenticatedGameRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_public/auth': typeof PublicAuthRouteWithChildren
  '/_public/logout': typeof PublicLogoutRoute
  '/_authenticated/game/cemetery': typeof AuthenticatedGameCemeteryRoute
  '/_authenticated/game/crafting': typeof AuthenticatedGameCraftingRoute
  '/_authenticated/game/guide': typeof AuthenticatedGameGuideRoute
  '/_authenticated/game/play': typeof AuthenticatedGamePlayRouteWithChildren
  '/_authenticated/game/ranking': typeof AuthenticatedGameRankingRoute
  '/_authenticated/game/spells': typeof AuthenticatedGameSpellsRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
  '/_public/auth/verify-email': typeof PublicAuthVerifyEmailRoute
  '/_authenticated/game/play/character-stats': typeof AuthenticatedGamePlayCharacterStatsRoute
  '/_authenticated/game/play/equipment': typeof AuthenticatedGamePlayEquipmentRouteWithChildren
  '/_authenticated/game/play/hub': typeof AuthenticatedGamePlayHubRoute
  '/_authenticated/game/play/inventory': typeof AuthenticatedGamePlayInventoryRoute
  '/_authenticated/game/play/shop': typeof AuthenticatedGamePlayShopRoute
  '/_authenticated/game/play/battle/$character': typeof AuthenticatedGamePlayBattleCharacterRoute
  '/_authenticated/game/play/equipment/select': typeof AuthenticatedGamePlayEquipmentSelectRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/403'
    | '/game'
    | '/profile'
    | '/users'
    | '/auth'
    | '/logout'
    | '/game/cemetery'
    | '/game/crafting'
    | '/game/guide'
    | '/game/play'
    | '/game/ranking'
    | '/game/spells'
    | '/users/$id'
    | '/auth/verify-email'
    | '/game/play/character-stats'
    | '/game/play/equipment'
    | '/game/play/hub'
    | '/game/play/inventory'
    | '/game/play/shop'
    | '/game/play/battle/$character'
    | '/game/play/equipment/select'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/403'
    | '/game'
    | '/profile'
    | '/users'
    | '/auth'
    | '/logout'
    | '/game/cemetery'
    | '/game/crafting'
    | '/game/guide'
    | '/game/play'
    | '/game/ranking'
    | '/game/spells'
    | '/users/$id'
    | '/auth/verify-email'
    | '/game/play/character-stats'
    | '/game/play/equipment'
    | '/game/play/hub'
    | '/game/play/inventory'
    | '/game/play/shop'
    | '/game/play/battle/$character'
    | '/game/play/equipment/select'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/403'
    | '/_authenticated/game'
    | '/_authenticated/profile'
    | '/_authenticated/users'
    | '/_public/auth'
    | '/_public/logout'
    | '/_authenticated/game/cemetery'
    | '/_authenticated/game/crafting'
    | '/_authenticated/game/guide'
    | '/_authenticated/game/play'
    | '/_authenticated/game/ranking'
    | '/_authenticated/game/spells'
    | '/_authenticated/users/$id'
    | '/_public/auth/verify-email'
    | '/_authenticated/game/play/character-stats'
    | '/_authenticated/game/play/equipment'
    | '/_authenticated/game/play/hub'
    | '/_authenticated/game/play/inventory'
    | '/_authenticated/game/play/shop'
    | '/_authenticated/game/play/battle/$character'
    | '/_authenticated/game/play/equipment/select'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/_public"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/403",
        "/_authenticated/game",
        "/_authenticated/profile",
        "/_authenticated/users"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/auth",
        "/_public/logout"
      ]
    },
    "/_authenticated/403": {
      "filePath": "_authenticated/403.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/game": {
      "filePath": "_authenticated/game.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/game/cemetery",
        "/_authenticated/game/crafting",
        "/_authenticated/game/guide",
        "/_authenticated/game/play",
        "/_authenticated/game/ranking",
        "/_authenticated/game/spells"
      ]
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users": {
      "filePath": "_authenticated/users.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/users/$id"
      ]
    },
    "/_public/auth": {
      "filePath": "_public/auth.tsx",
      "parent": "/_public",
      "children": [
        "/_public/auth/verify-email"
      ]
    },
    "/_public/logout": {
      "filePath": "_public/logout.tsx",
      "parent": "/_public"
    },
    "/_authenticated/game/cemetery": {
      "filePath": "_authenticated/game/cemetery.tsx",
      "parent": "/_authenticated/game"
    },
    "/_authenticated/game/crafting": {
      "filePath": "_authenticated/game/crafting.tsx",
      "parent": "/_authenticated/game"
    },
    "/_authenticated/game/guide": {
      "filePath": "_authenticated/game/guide.tsx",
      "parent": "/_authenticated/game"
    },
    "/_authenticated/game/play": {
      "filePath": "_authenticated/game/play.tsx",
      "parent": "/_authenticated/game",
      "children": [
        "/_authenticated/game/play/character-stats",
        "/_authenticated/game/play/equipment",
        "/_authenticated/game/play/hub",
        "/_authenticated/game/play/inventory",
        "/_authenticated/game/play/shop",
        "/_authenticated/game/play/battle/$character"
      ]
    },
    "/_authenticated/game/ranking": {
      "filePath": "_authenticated/game/ranking.tsx",
      "parent": "/_authenticated/game"
    },
    "/_authenticated/game/spells": {
      "filePath": "_authenticated/game/spells.tsx",
      "parent": "/_authenticated/game"
    },
    "/_authenticated/users/$id": {
      "filePath": "_authenticated/users/$id.tsx",
      "parent": "/_authenticated/users"
    },
    "/_public/auth/verify-email": {
      "filePath": "_public/auth/verify-email.tsx",
      "parent": "/_public/auth"
    },
    "/_authenticated/game/play/character-stats": {
      "filePath": "_authenticated/game/play/character-stats.tsx",
      "parent": "/_authenticated/game/play"
    },
    "/_authenticated/game/play/equipment": {
      "filePath": "_authenticated/game/play/equipment.tsx",
      "parent": "/_authenticated/game/play",
      "children": [
        "/_authenticated/game/play/equipment/select"
      ]
    },
    "/_authenticated/game/play/hub": {
      "filePath": "_authenticated/game/play/hub.tsx",
      "parent": "/_authenticated/game/play"
    },
    "/_authenticated/game/play/inventory": {
      "filePath": "_authenticated/game/play/inventory.tsx",
      "parent": "/_authenticated/game/play"
    },
    "/_authenticated/game/play/shop": {
      "filePath": "_authenticated/game/play/shop.tsx",
      "parent": "/_authenticated/game/play"
    },
    "/_authenticated/game/play/battle/$character": {
      "filePath": "_authenticated/game/play/battle/$character.tsx",
      "parent": "/_authenticated/game/play"
    },
    "/_authenticated/game/play/equipment/select": {
      "filePath": "_authenticated/game/play/equipment/select.tsx",
      "parent": "/_authenticated/game/play/equipment"
    }
  }
}
ROUTE_MANIFEST_END */
