-- Criar enum para roles
CREATE TYPE user_role AS ENUM ('PLAYER', 'ADMIN');

-- Criar tabela de usuários
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    username VARCHAR(50) UNIQUE NOT NULL,
    display_name VARCHAR(100),
    email VARCHAR(255) UNIQUE NOT NULL,
    avatar_url TEXT,
    role user_role DEFAULT 'PLAYER',
    highest_floor INT DEFAULT 0,
    total_games INT DEFAULT 0,
    total_victories INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true NOT NULL
);

-- Criar índices
CREATE INDEX users_uid_idx ON users(uid);
CREATE INDEX users_username_idx ON users(username);
CREATE INDEX users_email_idx ON users(email);

-- Criar função para atualizar updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Criar trigger para atualizar updated_at
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Habilitar RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Política para service_role ter acesso total
CREATE POLICY "Service role tem acesso total" ON users
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- Política para leitura pública
CREATE POLICY "Leitura pública" ON users
    FOR SELECT 
    USING (true);

-- Política para usuários autenticados
CREATE POLICY "Usuários autenticados gerenciam seus dados" ON users
    FOR ALL
    USING (auth.uid() = uid)
    WITH CHECK (auth.uid() = uid); 